version: '3.8'
services:
  eureka-registry:
    build: ./Registry
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
      - frontend
  eureka-server:
    build: ./Server
    depends_on:
      - eureka-registry
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka
      - spring.datasource.url=jdbc:mysql://auction-house-db.caj2ymy7edg0.eu-west-3.rds.amazonaws.com:3306/TESTING
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.username=MainUsername
      - spring.datasource.password=Testing12#$$
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - frontend
  frontend:
    build: ./Web
    ports:
      - 4200:4200
    expose:
      - 4200
    networks:
      - frontend
networks:
  frontend:
    driver: bridge