spring:
  application:
    name: Server
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:OraDoc
    username: Testing
    password: Testing123
    driver-class-name: oracle.jdbc.OracleDriver
    schema: TESTING
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: TESTING

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

liquibase:
  enabled: true
  changelog: "classpath:db/changelog/db.changelog-master.xml"

auctionHouse.app.jwtSecret: testSecret
auctionHouse.app.jwtExpirationMs: 86400000